[versions]
android = "7.2.2"
androidx-activity = "1.5.1"
androidx-appcompat = "1.4.2"
androidx-compose = "1.3.0-beta02"
androidx-compose-material3 = "1.0.0-beta02"
androidx-datastore = "1.0.0"
androidx-startup = "1.1.1"
accompanist = "0.26.3-beta"
cachefix = "2.5.6"
dagger = "2.43"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
ktlint = "10.3.0"
minidns = "1.0.3"
okhttp = "4.10.0"
turbine = "0.8.0"
wire = "4.4.0"
workflow = "1.7.1"

[libraries]
android = { module = "com.android.tools.build:gradle", version.ref = "android" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
cachefix = { module = "gradle.plugin.org.gradle.android:android-cache-fix-gradle-plugin", version.ref = "cachefix" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
minidns-android21 = { module = "org.minidns:minidns-android21", version.ref = "minidns" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
workflow-core-jvm = { module = "com.squareup.workflow1:workflow-core-jvm", version.ref = "workflow" }
workflow-ui-compose = { module = "com.squareup.workflow1:workflow-ui-compose", version.ref = "workflow" }

[plugins]
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
