[versions]
android = "7.4.0"
androidx-activity = "1.6.1"
androidx-appcompat = "1.6.0"
androidx-compose = "1.3.3"
androidx-compose-foundation = "1.3.1"
androidx-compose-material = "1.3.1"
androidx-compose-material3 = "1.0.1"
androidx-core = "1.8.0"
androidx-datastore = "1.0.0"
androidx-media = "1.6.0"
androidx-startup = "1.1.1"
accompanist = "0.28.0"
cachefix = "2.6.3"
dagger = "2.44.2"
dokka = "1.7.20"
kotlin = "1.7.20"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.0"
ktlint = "0.48.1"
licensee = "1.6.0"
minidns = "1.0.3"
okhttp = "4.10.0"
okio = "3.2.0"
spotless = "6.13.0"
turbine = "0.12.1"
webrtc = "104.0.0"
wire = "4.4.3"
workflow = "1.7.1"

[libraries]
android = { module = "com.android.tools.build:gradle", version.ref = "android" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
cachefix = { module = "gradle.plugin.org.gradle.android:android-cache-fix-gradle-plugin", version.ref = "cachefix" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinx-serialization" }
licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
minidns-hla = { module = "org.minidns:minidns-hla", version.ref = "minidns" }
minidns-android21 = { module = "org.minidns:minidns-android21", version.ref = "minidns" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
webrtc = { module = "com.pexip.webrtc:webrtc", version.ref = "webrtc" }
workflow-core-jvm = { module = "com.squareup.workflow1:workflow-core-jvm", version.ref = "workflow" }
workflow-ui-compose = { module = "com.squareup.workflow1:workflow-ui-compose", version.ref = "workflow" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-binarycompatibilityvalidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.12.1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
