name: 'main'

on:
  push:
    branches:
      - main

env:
  CI: 'true'
  GRADLE_OPTS: ${{ vars.GRADLE_OPTS }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - run: ./gradlew build
      - run: ./gradlew publish --no-parallel
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SONATYPE_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}

      - run: ./gradlew dokkaHtmlMultiModule
        if: ${{ startsWith(github.event.head_commit.message, 'release:') }}

      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ startsWith(github.event.head_commit.message, 'release:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule

  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: true

      - run: snyk-linux monitor --all-sub-projects --remote-repo-url=$GITHUB_REPOSITORY --target-reference=$GITHUB_REF_NAME --configuration-matching='^(jvm|.*[rR]elease)?[rR]untimeClasspath$'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_CFG_ORG: ${{ secrets.SNYK_CFG_ORG }}
