name: 'main'

on:
  push:
    branches:
      - main

env:
  CI: 'true'
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - run: ./gradlew build
      - run: ./gradlew publish --no-parallel
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_MavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_MavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}

      - run: ./gradlew dokkaHtmlMultiModule
        if: ${{ startsWith(github.event.head_commit.message, 'release:') }}

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ startsWith(github.event.head_commit.message, 'release:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule

  snyk_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - run: snyk test --all-sub-projects --sarif-file-output=snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_CFG_ORG: ${{ secrets.SNYK_CFG_ORG }}

      - uses: github/codeql-action/upload-sarif@v2
        with:
          category: snyk
          sarif_file: snyk.sarif

  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - run: snyk monitor --all-sub-projects --remote-repo-url=$GITHUB_REPOSITORY
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_CFG_ORG: ${{ secrets.SNYK_CFG_ORG }}
